version: "3.8"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: example-ai-stuff-repeat
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
